on: 
  push:
  schedule:
    - cron:  '29 16 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add stz https://github.com/stz2012/recpt1
          git remote add m1ur https://github.com/hendecarows/recpt1
          git fetch stz master
          git fetch m1ur feature-px4
          git merge stz/master
          git push origin master
          git merge m1ur/feature-px4
          git push origin master